### ISSUE TITLE
segment specified in url: thumbs infinite scrolling issue

### ISSUE THREAD

**Issue by luxigo** [doxel/doxel-angular#30]
When reloading the page with a segment specified in the URL, we cannot load every segment or thumbnail up to the specified one.

Infinite scrolling must be enhanced, so that extra segments are unloaded, and so that we load only a chunk of segments around the segment specified in the URL, and according to the sort order:  "timestamp", or (later) "distance from map center"

Maybe we should associate a list index to each segment  for each sort order, to be updated each time a segment becomes ready to be viewed (or a "next" and "prev" id)

**Comment by luxigo** [comment]
- [x] Load segments before first segment in list (ie: selected one on pagereload)
- [x] Load segments after last segment in list (ie: selected one on pagereload)
- [x] Add more segments on top and on bottom while scrolling
- [ ] Remove segments at the other end while scrolling

**Comment by bugdanov** [comment]
Remaining points moved to 1.1 milestone

**Comment by bugdanov** [comment]
removing segments at the top while scrolling requires some malihu scrollbar hacking, should open another issue for it
