### ISSUE TITLE
selection issues

### ISSUE THREAD

**Issue by bugdanov** [doxel/doxel-angular#35]
thumb selection is somewhat messed up because the way it is managed through the embeeded scopes hierarchy (gallery -> gallery.thumbs -> &lt;segment-set> ->  &lt;segment-preview> -> &lt;picture>)

Maybe selection information should be kept in an angular service or in a scope object at the lowest level (gallery)

**Comment by sacha-l** [comment]
Unable to upload images: internal server error!

**Comment by bugdanov** [comment]
@12al29 Sorry for the inconvenience, maybe it was a temporary problem, else you should open a specific Issue for it with the "new issue" button on the top-right corner of this page or this link https://github.com/doxel/doxel-angular/issues/new) and join the server reply (from the network tab of your browser developper tools) or a copy of the error object details listed on the javascript console output. Thanks.
